### ISSUE TITLE
StanfordOrganizationsToVivo transformer should return valid JSON-LD

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss-labs/rialto-etl#10]
This will require prepending the `@context` object and wrapping all mapped results into a `@graph` array.

Right now it just spits out a bunch of individual records in JSON.

**Comment by mjgiarlo** [comment]
@cbeer @billdueber @jrochkind I'd welcome advice on how to deal with this: I'd like to write JSON-LD, which will look like the following:

```json
{
  @context: {
    'foo': 'http://bar.example.org/foo'
  },
  '@graph': [
    {
      '@id': '1'
    },
    {
      '@id': '2'
    }
  ]
}
```

Where the documents within the `@graph` array are records output from Traject.

As far as I can tell, `Traject::Indexer#process` is built assuming that it will read in records and output one line per record (when using the `LineWriter` or a subclass thereof, anyway). Do you have suggestions for how I might handle this? The "easy" solution is to post-process what comes out of Traject but you tell me: should Traject be able to handle use cases like this? I welcome your ideas here, and I'd be happy to work on this if this sounds like a potentially useful addition to Traject, assuming I can find a fruitful strategy for implementing this.

**Comment by jrochkind** [comment]
@mjgiarlo I am not sure how to use traject for outputting RDF either, but I can clarify the current assumptions of RDF. It doesn't really assume it will write one "line" per record, there isn't really any built-in abstraction around "lines" per se. 

It assumes:

1) The input is a single ruby object, of whatever type you like
2) The intermediate form used during processing to accumulate output is a ruby hash, one hash per record
3) That one hash per record is given to a configured writer. The writer can do whatever it wants with that one-hash-per-record. 

Does this help?

**Comment by jrochkind** [comment]
If you _already_ have that hash in the context... does the existing JsonWriter output it how you want? If not, creating a new writer to do so should not be hard. If you don't already have the hash you want in the context... that's what I'd expect to be the hard part, yeah.

**Comment by jrochkind** [comment]
Ah, "Where the documents within the @graph array are records output from Traject." -- yeah, the existing writer wont' do that. You could certainly create a writer to do that. The downside I see is that the writer would have to keep _all_ output in memory, which could get to be a problem with thousands/millions of records. 

If that's not a problem for you, the other part of writer API I didn't mention is a `#close` method, which traject #process will already call when it's done.  So you have a writer that just implements `#put` to keep all contexts (or their `output_hash`s) in an in-memory array, then on `#close` writes them all the way you want. 

I don't like that it has to keep everything in memory until the end though. traject in general is written to have constant-ish memory use even processing millions of records, rather than memory use that scales with number of records. I guess the writer could instead write the file to disk little by little on each record, keeping an open file handle, until it gets `#close`?

**Comment by mjgiarlo** [comment]
@jrochkind Right, you've gotten exactly the downside with this approach. The RDF part isn't that interesting -- I'd have the same challenge with any output format that wanted to wrap the results, e.g.:

```xml
<myBespokeFormat>
  <records>
    <record foo='bar'> <!-- This is output from Traject and there could be one to many of these -->
  </records>
</myBespokeFormat>
```

Because `Traject::Indexer#process` calls `writer.close`, outputting the stuff that follows the records isn't a big deal. But there's no hook to output the stuff that precedes the records.

With a fairly small tweak to the `#process` method, we could handle that by adding code like the following around https://github.com/traject/traject/blob/master/lib/traject/indexer.rb#L408:

```ruby
writer.preamble if writer.respond_to?(:preamble)
```

I don't love the name and this is super dumb/simple, admittedly. A potential downside here is that I can spit out a preamble and spit out a postamble in the writer's `#close` method, but there's no guarantee that my output is valid. For instance, I can create a JSON-LD writer that uses this strategy but there's no reasonable way to validate the overall output is a JSON-LD document. I can reasonably conclude, assuming I subclass/extend `Traject::JsonWriter`, that the records themselves are valid JSON, but unless I hold the full output including preamble and postamble somewhere and then validate it later, I could be outputting garbage. I'm not sure if that indicates a weakness in this approach or not, as I'm not sure how much Traject cares about output validity, generally speaking.

**Comment by billdueber** [comment]
So, the more I think about this, the more I like how it exposes some seams that deserve more thought. For example, my first thought was to do BFMI it (Brute Force and Massive Ignorance) 
like this:

```ruby

# prep work
graph_indexer = Traject::Indexer.new
# load up the "to_field" definitions and whatnot
[my, index, definition, files].each {|x| graph_indexer.load_config_file x}

# Add the settings
graph_indexer.settings do |s|
  provide "whatever", "here"
  store "something", "else"
end

# real work loop
wherever_you_get_stuff_from.each do |container_rec|
  container_rec.graph = container.graph.map{|g| graph_indexer.map_record(g)}
  write_it_out_somehow(container_rec)
end

```

This is annoying in a lot of ways, not the least of which is that if you want to use a regular traject writer, they all take in things to write as `writer#put(context)` (and what you have is essentially just the context_hash, so you'd have to wrap it in an object that responds to `#context_hash`). 

So, something like

```ruby
@writer = Traject::SolrJsonWriter.new(settings_hash)
StupidCHStruct = Struct.new(:context_hash)

def write_it_out_somehow(rec)
  @writer.put StupidCHStruct.new(rec)
end
```

**Comment by mjgiarlo** [comment]
I whipped up https://github.com/sul-dlss-labs/rialto-etl/pull/17 based on @jrochkind's last comment, noting in the commit & PR that it is suboptimal in that it holds records in memory. Fortunately the records here are small and are not likely to number in the millions, so this may be good enough for now.

(Oh, hey, @billdueber left a comment above that I should read! Thanks, Bill.)

**Comment by jrochkind** [comment]
Do you really need `preamble`, or can the writer just notice the first time it receives a `put`?

**Comment by mjgiarlo** [comment]
@jrochkind I suppose the writer could do that by keeping some small amount of state. For now I'm not inclined to ask for any changes to Traject. Thanks for your advice!

I am closing this issue since the transformer writes valid JSON-LD. (Though it turns out I need ntriples more than I need JSON-LD...)

**Comment by jrochkind** [comment]
Cool. It'd be less state than keeping every record in memory as you're doing now, but if you are processing quantities of records where that's doable, seems reasonable! 

If it's inconvenient to write a writer that outputs ntriples, might be easiest just to pipe it to something that will translate json-ld to ntriples. If you have such a tool that takes stdin, you could write to stdout and pipe `traject` command, or just have the writer open a pipe. Or even have the writer write to a temp file and then call the translator on it, like hydra-derivatives does for it's things.

**Comment by mjgiarlo** [comment]
Thanks, @jrochkind.

By the by, here's my ntriples writer: https://github.com/sul-dlss-labs/rialto-etl/blob/master/lib/rialto/etl/writers/ntriples_writer.rb
