### ISSUE TITLE
Rename sparql statement writer to reflect that it expects people entities

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss-labs/rialto-etl#100]
Do this to set up work to create sparql statement writer for publications and orgs (and grants eventually).

Blocked by https://github.com/sul-dlss-labs/rialto-etl/issues/108

**Comment by mjgiarlo** [comment]
As I understand it, this is blocked by work @justinlittman is doing to look into whether a different pattern of transforming to SPARQL is feasible.

**Comment by justinlittman** [comment]
Resolved by #108, as SparqlStatementWriter is not specific to people entities.
