### ISSUE TITLE
Investigate how we are using Traject (with transformation logic in writers in addition to transformers)

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss-labs/rialto-etl#108]
Discussed after stand-up today.

**Comment by justinlittman** [comment]
Trying to sketch out advisor / advisee in JSON-LD, I (partially) get:
```
{
  "@id": "http://sul.stanford.edu/rialto/person/the_advisor",
  "http://vivoweb.org/ontology/core#relatedBy": [
    {
      "@id": "http://sul.stanford.edu/rialto/context/relationships/advisee_1_the_advisor",
      "@type": "http://vivoweb.org/ontology/core#AdvisingRelationship"
    }
  ]
}
```
I now want to say that an advisee (say `http://sul.stanford.edu/rialto/person/advisee1` is VIVO.relatedBy the advising relationship. This (I believe) would need to be a separate JSON-LD doc. Which (I believe) isn't possible from a Traject transform.

Next approach is to try with 2 transform passes.

**Comment by justinlittman** [comment]
As I think this through, actually writing to JSON-LD isn't necessary. All that is necessary is understanding the JSON-LD-like hash, which really isn't all that different from the hash understood by the existing SparqlStatementWriter.

Key differences:
* SparqlStatementWriter doesn't deal with `@fields` that get special handling (except, `@id` and `@label`).
* SparqlStatementWriter can recursively handle nested entities (i.e., where values include dicts).

Still to be determined:
* Is redundancy in the config excessive?
* Can entities like advisees be handled?
