### ISSUE TITLE
StanfordOrganizations transformer should include parent/child information

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss-labs/rialto-etl#12]
This will require changes to the StanfordOrganizationsJsonReader.

**Comment by cmh2166** [comment]
Yes, and want to discuss this question wrt the data transform approach - i.e., always take the ROOT and iterate on a single input to the full graph output, or iterate on entities separately with multiple API calls / outputs? 

Also question around incremental updates to the graph as opposed to overwriting graph (both have pros/cons).
