### ISSUE TITLE
WOS transform should create authors if they don't already exist

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#127]
- [x] Create a URI immediately in a named graph associated with WoS
- [ ] Associate them to their organization (create if necessary) using a vivo:Position entity (position could be something generic like "employee")
- [x] associate them to the publication with an vivo:Authorship entity

**Comment by justinlittman** [comment]
Still need to map to organizations via position.

**Comment by mjgiarlo** [comment]
OK! My bad.

**Comment by justinlittman** [comment]
No, I thought the work was done too.
