### ISSUE TITLE
Position to organization mapping problems

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/rialto-etl#143]
refs #139

Currently, we map a person to a part of Stanford (e.g., a department) via her position. The position and department is taken from the `title` field of the researcher profile. The organization is mapped via the org code.

For some positions, the org codes do not map to known organizations. There are two variations on this problem:

1. Org code R001.
4,207 of 11,600 people have an org code of R001. This appears to be a manually created organization within the profiles system (or whatever system fed the profiles system). Here are some examples:
```
"titles": [{
		"academicInstituteDisplay": false,
		"affiliation": "capStaff",
		"bannerDisplay": true,
		"label": {
			"html": "CLINICAL NURSE, NORTH INTENSIVE CARE-SHC",
			"text": "CLINICAL NURSE, NORTH INTENSIVE CARE-SHC"
		},
		"organization": {
			"interDepartmentalProgram": false,
			"label": {
				"html": "NORTH INTENSIVE CARE-SHC",
				"text": "NORTH INTENSIVE CARE-SHC"
			},
			"org": "NORTH INTENSIVE CARE-SHC",
			"orgCode": "R001"
		},
		"title": "CLINICAL NURSE",
		"type": "staff"
	}],
```
In this case, no organization can be found called "North Intensive Care".

```
	"titles": [{
		"academicInstituteDisplay": false,
		"affiliation": "capRegistry",
		"bannerDisplay": true,
		"label": {
			"html": "Graduate, Biochemistry",
			"text": "Graduate, Biochemistry"
		},
		"organization": {
			"interDepartmentalProgram": false,
			"label": {
				"html": "Biochemistry",
				"text": "Biochemistry"
			},
			"org": "Biochemistry",
			"orgCode": "R001"
		},
		"title": "Graduate",
		"type": "reg-student"
	}],
```
In this case, there is an existing Biochemistry department but not with the org code R001.

2. Other unknown org codes
For ~700 other positions, the org codes given for the position are unknown. Some examples are ZZUJ, MRLO, GAVG, ZZSK.

```
	"titles": [{
		"academicInstituteDisplay": false,
		"affiliation": "capRegistry",
		"bannerDisplay": true,
		"label": {
			"html": "Affiliate, Central Mgmt-Misc AR",
			"text": "Affiliate, Central Mgmt-Misc AR"
		},
		"organization": {
			"interDepartmentalProgram": false,
			"label": {
				"html": "Central Mgmt-Misc AR",
				"text": "Central Mgmt-Misc AR"
			},
			"org": "Central Mgmt-Misc AR",
			"orgCode": "ZZUJ"
		},
		"title": "Affiliate",
		"type": "reg-affiliate"
	}],
```

**Comment by justinlittman** [comment]
Currently, positions with invalid organizations are ignored. The invalid organizations are logged. Is this the correct approach?

**Comment by peetucket** [comment]
From the profiles team:

```Regarding determining which department, etc, that people are in, the Org code in the title section is the preferable method.  This will also give you the title of the org code and the type of affiliation that people have at Stanford.

Regarding the org endpoint, I did some testing with the orgs you noted that were not coming back in the API call for this endpoint.  The issue there is that the example orgs you listed, like ZZSK, did not have a parent org defined in our ref department table.  Once I defined this for ZZSK it came up in the org search in the API org endpoint.  Speaking with Don on this, this is probably a bug in our code logic that is not adding new orgs correctly by adding their parent org and adding the child org with that parent org.  In this case the parent org, ZZSA did not exist and I had to add this as well before adding it to ZZSK.  We will have to look at the whole issue further to determine the right solution.  So, for now, I would have to correct this manually if you have a list of orgs with this issue that you are trying to pull through the org endpoint.

Also, please note that R001 is not a real org code.  It was added when we started bringing in Registry data and creating abbreviated Registry only profiles for folks such as undergrads and unpaid affiliates who do not have full PeopleSoft information or for whom we do not have full profile layouts defined as of yet.  This was put in for Org Codes in this data that were not in Profiles.  However, this is a incorrect logic as well.  We will be fixing this in a future release when we rewrite our PeopleSoft and Registry sync processes.

On your question regarding the classes of people that get profile pages, basically everyone gets a profile in Stanford Profiles.  There are different layouts depending on your role, i.e Faculty, Staff, Grad Student, Postdoc, Resident, Fellow, and BioMed and then Registry layout for affiliates, undergrads, unpaid affiliates, and temp / casual staff.  When you say you are getting them back, but they don't have a profile page, the only thing I can see that would account for this is that the profile is 'private' as you are using the stanford_full_hidden API community that gives you full stanford-only and Publicly visible profiles and mini hidden / private profiles.  If you do not want the private / hidden profiles, you can request that the community be limited to stanford_full and we can change this for you.```

**Comment by justinlittman** [comment]
Is it possible to limit ourselves to a smaller set of Stanford people, like maybe just faculty, postdocs, and fellows? By trying to make sense of everyone's data, we're taking the hit of a really long tail of edge cases for not much of a gain in useful data. (Adding more classes of people would always be possible in the future if required.)

With regards to mapping Stanford people to Stanford organizations, this might address the R001 problem. It would also allow us to produce a finite list of orphaned org codes that could be manually remediated by the profiles team. And, in general, it would speed up all of our processing.

Anyway, throwing this out for discussion / consideration.

--Justin

________________________________

**Comment by peetucket** [comment]
The idea of only including faculty, postdocs, and fellows is a good one and was on my agenda to discuss tomorrow with stakeholders.  Not only will this make the scope of the problem smaller, it will also decrease the amount of data we need to then pull from both SeRA and WoS.  

How would we do this?  Would be simply skip over profiles that don't match our filter of people to include when iterating over all people?

**Comment by justinlittman** [comment]
There are several different ways this could be implemented. We'd probably want to briefly discuss before selecting an approach.


Best.

--Justin

________________________________

**Comment by jcoyne** [comment]
We've made this into the "Unmapped department"
