### ISSUE TITLE
ETL problem logging

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/rialto-etl#154]
Consistent approach for logging issues encountered during an ETL run. These might include:
* Entities that are expected to exist that don't exist.
* 500 errors from APIs, entity resolvers
* Other errors that are non-fatal.

Presumably, logs should be grouped by the operation (e.g., extract, transform, load) and the time that the operation was run.

**Comment by tingulfsen** [comment]
To add to this ticket - let's set up an application-wide logger that logs to a log/ directory - similar to what we do for Rails applications.
