### ISSUE TITLE
Address mapping question

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/rialto-etl#161]
Currently:
* A Stanford person gets a complete address vcard from profiles.
* Any person gets a country only vcard from each publication.

This means that a user may have multiple address vcards. Some of those may contain the same information; others may be conflicting (e.g., different countries).

What is the correct approach? Should a user have only one address or more than one address? If only one address, how do we decide which address to use?

refs #147

**Comment by mjgiarlo** [comment]
@justinlittman Can you add this to the agenda for the next arch. check-in?

**Comment by justinlittman** [comment]
Decision from 10/5 architecture meeting: Get rid of vcard / rest of address and record country as DC.spatial with geonames URI as object.
