### ISSUE TITLE
Add SNS loader

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/rialto-etl#187]
As part of https://github.com/sul-dlss/rialto/issues/291

The SNS loader will extract subjects from SPARQL statements, batch them up, and send via SNS.

This is a work-around for not having the SPARQL proxy in the docker dev environment.

**Comment by mjgiarlo** [comment]
@justinlittman It appears that https://github.com/sul-dlss-labs/rialto-etl/pull/188 moved this issue into the review column, and then 188 was closed. What do you think we should do with this issue now?

**Comment by justinlittman** [comment]
Opted not to pursue this approach in favor of running the Sparql Loader in a docker container, so closing.
