### ISSUE TITLE
All authors have hashcode uris

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#226]
Shouldn't one of them be a standford URI?

https://rialto.dev.sul.stanford.edu/#/catalog/http:%2F%2Fsul.stanford.edu%2Frialto%2Fpublications%2Fe662a31d9666b7a2310783e43e12fbd1

**Comment by peetucket** [comment]
problem with entity resolver?

**Comment by justinlittman** [comment]
I don't see this locally, so probably (1) ER problem or (2) running old code.

**Comment by jcoyne** [comment]
I suspect it was running old code. The last image for entity resolver was published 7 days ago, but the last fix in master is 3 days old.

**Comment by jcoyne** [comment]
Fixed in the latest load.
