### ISSUE TITLE
Add WOS API authentication credentials to shared_configs

### ISSUE THREAD

**Issue by jgreben** [sul-dlss-labs/rialto-etl#25]
Fixes https://github.com/sul-dlss-labs/rialto-etl/issues/25

**Comment by jgreben** [comment]
I went ahead and added the WOS API key to:
https://github.com/sul-dlss/shared_configs/blob/rialto-etl-prod/config/settings/production.yml

Please let me know if this looks like the right key. I got it from the sul-pub-prod branch.

**Comment by peetucket** [comment]
looks right to me

**Comment by jgreben** [comment]
👍 Closing issue.
