### ISSUE TITLE
Separate departments from institutes

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss-labs/rialto-etl#252]
Where an institute should be a http://vivoweb.org/ontology/core#Institute

In support of https://jirasul.stanford.edu/jira/browse/RIALTO-15

**Comment by jcoyne** [comment]
How do we classify an organization as an Institute?

**Comment by justinlittman** [comment]
Per @peetucket 
> Since we do not know which academic units are institutes and which are departments from the Profiles organization API, we will need to manually curate this list and add it to configuration in order to run this report.

**Comment by justinlittman** [comment]
Turns out an institute can be a DEPARTMENT or a DIVISION.

**Comment by peetucket** [comment]
I can curate the list -- where can I find it?
