### ISSUE TITLE
Generate list of sources + types of data from each for first pass of extractors

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/rialto-etl#3]

**Comment by mjgiarlo** [comment]
I'm struggling to remember what this issue means. @cmh2166 ?

**Comment by cmh2166** [comment]
enumerate sources + what data we pull from it.

**Comment by cmh2166** [comment]
i.e. 'web of science', 'profiles', 'sul-pub', etc.

**Comment by mjgiarlo** [comment]
Like, the rialto-etl CLI tool should support this, or we need this in a document, or what? I was just thinking of adding a `-l` flag to the extractor and transformer classes in rialto-etl that would spit out this kind of information. Would that close this issue (and be useful), or did I misunderstand?

**Comment by cmh2166** [comment]
document it to know what to add as dev tickets
