### ISSUE TITLE
Gain access to new WOS API and associated documentation

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss-labs/rialto-etl#40]

**Comment by peetucket** [comment]
1. Swagger API minimal documentation: https://developer.clarivate.com/swagger-ui/?url=/apis/wos/swagger

2. Will ping Clarivate about access keys

The current REST API Documentation is linked from here and I suspect the fields available and queryable parameters will be the same or identical: https://github.com/sul-dlss/sul_pub/wiki/Clarivate-APIs

**Comment by mjgiarlo** [comment]
@peetucket will reach out to Clarivate again per today's storytime discussion.

**Comment by peetucket** [comment]
Key now in rialto-etl-prod shared configs branch.

Documentation here: https://developer.clarivate.com/apis?filter=on&Web+of+Science=on (but may need to register for a free account to see it)
