### ISSUE TITLE
Transformer should be able to extract JSON as scalars

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss-labs/rialto-etl#6]
Currently, TrajectPlus's `#extract_json` macro always returns an Array, so you wind up with JSON like the following:

```json
{
  "@id": ["foobar"]
}
```

instead of:

```json
{
  "@id": "foobar"
}
```

**Comment by mjgiarlo** [comment]
This method uses the `JsonPath` gem which implements the [JSONPath spec](http://goessner.net/articles/JsonPath/). The spec dictates that all JSONPaths return arrays.

**Comment by cbeer** [comment]
Can you use `to_field [...], single: true`? (experimental and undocumented, and can now be rewritten a little nicer now that traject#145 is in)

**Comment by mjgiarlo** [comment]
@cbeer Ah! Yes, I'll give that a shot. If you give me a high-level description of how `single` can be rewritten now that TP is based on Traject 2.3.4, I can have a go at that too. Or if you'd rather do that later on, that's fine too.

**Comment by mjgiarlo** [comment]
Works like a charm. Thank you, @cbeer! Closing.
