### ISSUE TITLE
Update Person rdfs:type.

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#68]
When a Person is imported with `rdfs:type` grad student
and on the next import they are a faculty,
they should no longer have `rdfs:type` grad student in Neptune.

**Comment by jcoyne** [comment]
Blocked by #53

**Comment by justinlittman** [comment]
Fixed by #53. Verified in unit test, see https://github.com/sul-dlss-labs/rialto-etl/blob/master/spec/configs/stanford_people_to_sparql_statements_spec.rb#L441.
