### ISSUE TITLE
Should reports be based on person address or institution address?

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#70]
https://github.com/sul-dlss-labs/rialto-etl/wiki indicates Person address.  But that doesn't necessarily make sense if that is not where their institution is located.

Maybe we also need institution address?

**Comment by peetucket** [comment]
Good question - I am assuming if this address is coming from the Profiles API, it will be their institution address (some building at Stanford usually) -- I don't think we should get (nor do we want) their personal home address...

**Comment by jcoyne** [comment]
All we have is person addresses from Web Of Science, so we're using that.
