### ISSUE TITLE
How do we consistently get a sunetid

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#77]
This is needed to get grant data.  We may need to split email address from the profile data.

**Comment by peetucket** [comment]
Which endpoint are we using to pull profiles data from?  I'm poking around on the swagger console and see a field called "uid" associated with person records that has the sunet

e.g. tail end of a person response to:

`.../cap-api/api/profiles/v1?uids=kcasciot&community=stanford`

```          },
          "title": "Member",
          "type": "faculty"
        }
      ],
      "uid": "SUNETID",
      "universityId": "1234567"
    }
  ]
}```

**Comment by justinlittman** [comment]
We're getting this from `uid` field of person profile. It is being added to a Stanford person with a DCTERMS:identifier and in the csv list as `sunetid` field.

Refs #53, #90.

I'd suggest that this ticket can be closed. If disagree, re-open.
