### ISSUE TITLE
Get SeRA production credentials

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#80]
currently the SeRA credentials in shared configs are only for `aswsuat.stanford.edu`

**Comment by peetucket** [comment]
ticket created: https://stanford.service-now.com/services?id=ticket&table=incident&sys_id=278fd6cbdb502b00f07e71fa8c9619b9

**Comment by peetucket** [comment]
still in process - expected sometime after sep. 20

**Comment by peetucket** [comment]
Scheduled - should be getting the credentials by EOD on Thrusday (9/27).
