### ISSUE TITLE
Complete and document SeRA mapping

### ISSUE THREAD

**Issue by peetucket** [sul-dlss-labs/rialto-etl#85]
outcome is documentation in the wiki

- [x] review and update SeRA transformer code in #84 
- [x] merge ETL mappings wiki page into data models/profiles page

**Comment by mjgiarlo** [comment]
Document the mapping here: https://github.com/sul-dlss-labs/rialto-etl/wiki#grants-sera-mapping

**Comment by mjgiarlo** [comment]
Going to discuss this at the next architecture check-in.

**Comment by mjgiarlo** [comment]
First pass done here: https://github.com/sul-dlss/rialto/wiki/RIALTO-Data-Models-&-Profiles#grants-sera-mapping
