### ISSUE TITLE
Investigate the topics/keyword values in WoS data to see what's there

### ISSUE THREAD

**Issue by peetucket** [sul-dlss-labs/rialto-etl#86]
How consistent is it?
This will drive the topic area selectors in the reports

**Comment by mjgiarlo** [comment]
http://ipscience-help.thomsonreuters.com/wosWebServicesExpanded/appendix1Group/ascaCategories/version/1
http://ipscience-help.thomsonreuters.com/wosWebServicesExpanded/8007-TRS.html?branch=authorityFile
http://ipscience-help.thomsonreuters.com/wosWebServicesExpanded/8010-TRS.html?branch=authorityFile

```shell
$ cat spec/fixtures/wos/000424386600014.json | jq '.static_data.fullrecord_metadata.category_info.subjects.subject | .[] | select(.ascatype == "extended").content' | sort | uniq

"Biochemistry & Molecular Biology"
"Biotechnology & Applied Microbiology"
"Chemistry"
"Computer Science"
"Genetics & Heredity"
"Mathematical & Computational Biology"
"Mathematics"
"Oncology"
"Pharmacology & Pharmacy"
"Research & Experimental Medicine"
"Science & Technology - Other Topics"

$ cat spec/fixtures/wos/000424386600014.json | jq '.static_data.fullrecord_metadata.category_info.subjects.subject | .[] | select(.ascatype == "traditional").content' | sort | uniq

"Biochemical Research Methods"
"Biotechnology & Applied Microbiology"
"Chemistry, Medicinal"
"Chemistry, Multidisciplinary"
"Computer Science, Information Systems"
"Computer Science, Interdisciplinary Applications"
"Genetics & Heredity"
"Mathematical & Computational Biology"
"Medicine, Research & Experimental"
"Multidisciplinary Sciences"
"Oncology"
"Pharmacology & Pharmacy"
"Statistics & Probability"
```

**Comment by mjgiarlo** [comment]
@peetucket Using our (admittedly small batch of) fixture data, I pulled out topic-like data and put that in the prior comment. Would you mind reviewing these and suggesting which one looks the most promising?

**Comment by mjgiarlo** [comment]
That is my interpretation as well, @peetucket. Let's go with extended subject types, then.

**Comment by mjgiarlo** [comment]
This is now done, and documented in the publication mapping: https://github.com/sul-dlss-labs/rialto-etl/wiki#publications-wosweb-of-science-mapping
