### ISSUE TITLE
CAP API correct domain + path?

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss-labs/rialto-etl#9]
`https://cap.stanford.edu/cap-api/api/cap/v1/` (as seen in the CAP console) or  `http://api.stanford.edu/cap/v1/` (as taken from previous work docs) (or does it matter)?

**Comment by cmh2166** [comment]
they throw different auth errors, fwiw.

**Comment by peetucket** [comment]
Huh, sorry, where is that api.stanford.edu/cap/v1 URL from?  I've done some tests using a browser based REST client using the https://cap.stanford.edu/cap-api/api/cap/v1/ URL and our credentials and it does work (you need to get a token first from https://authz.stanford.edu/oauth/token?grant_type=client_credentials).  Note that this is a different API than is used by the sul_pub app. 

Can we chat about the best way to privately document our API credentials (maybe shared_configs)?

**Comment by mjgiarlo** [comment]
@peetucket Er, good question. I see the api.stanford.edu-type URL here: https://docs.google.com/document/d/1zDt7Rru4MXFGzpdLl-OV5xSQ-CXFyT2ZsWg6lcpFyU0/edit#heading=h.evxadbkj2aaf Not sure where we got it from. We are currently using it successfully: https://github.com/sul-dlss-labs/rialto-etl/blob/c13641830fe2bdb781101fa136eaf02f0ee61795/lib/rialto/etl/extractors/abstract_stanford_extractor.rb#L24 using the same technique to get an OAuth token: https://github.com/sul-dlss-labs/rialto-etl/blob/c13641830fe2bdb781101fa136eaf02f0ee61795/lib/rialto/etl/extractors/abstract_stanford_extractor.rb#L83

I wonder if api.stanford.edu is a proxy in front of other APIs on campus? That is pure speculation, and I'm happy to use the other URL if that's the right way to go.

And yes, let's chat about API creds.

**Comment by mjgiarlo** [comment]
Yes, api.stanford.edu seems to be an "enterprise proxy" in front of other campus APIs. What are your thoughts on whether we should use this or not, @peetucket?

**Comment by peetucket** [comment]
If api.stanford.edu works, that seems fine to keep using.  Presumably this would be easily configurable if it needed to change in the future.

**Comment by mjgiarlo** [comment]
Thanks, @peetucket! Closing.
